Fix CI error
1. no_voting for lower-constraints CI
2.pep8 create: /home/zuul/src/opendev.org/openstack/freezer/.tox/pep8
pep8 installdeps: -c/home/zuul/src/opendev.org/openstack/requirements/upper-constraints.txt, -r/home/zuul/src/opendev.org/openstack/freezer/test-requirements.txt
ERROR: invocation failed (exit code 1), logfile: /home/zuul/src/opendev.org/openstack/freezer/.tox/pep8/log/pep8-1.log
================================== log start ===================================
Looking in indexes: https://mirror.bhs1.ovh.opendev.org/pypi/simple, https://mirror.bhs1.ovh.opendev.org/wheel/ubuntu-20.04-x86_64
Collecting astroid==2.1.0
  Downloading https://mirror.bhs1.ovh.opendev.org/pypifiles/packages/fc/53/8809bc008bad0300897281a7b320b286dc0e84e836396c0cff6279841e8a/astroid-2.1.0-py3-none-any.whl (176 kB)
Collecting pylint==2.3.1
  Downloading https://mirror.bhs1.ovh.opendev.org/pypifiles/packages/60/c2/b3f73f4ac008bef6e75bca4992f3963b3f85942e0277237721ef1c151f0d/pylint-2.3.1-py3-none-any.whl (765 kB)
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of astroid to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r /home/zuul/src/opendev.org/openstack/freezer/test-requirements.txt (line 23) and astroid==2.1.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested astroid==2.1.0
    pylint 2.3.1 depends on astroid<3 and >=2.2.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
WARNING: You are using pip version 20.3.3; however, version 21.0 is available.
You should consider upgrading via the '/home/zuul/src/opendev.org/openstack/freezer/.tox/pep8/bin/python -m pip install --upgrade pip' command.
================================ log end ===============================

Change-Id: I898d03d716ebc6c6285c4589cd30f7875b0c51d2