Fixes starting freezer-scheduler with --no-daemon
When using flag --no-daemon, freezer-scheduler --no-daemon start fails
with AttributeError: 'NoDaemon' object has no attribute 'restart'
(freezer_scheduler.py: L251). This patch adds missing dummy methods for
reload and restart actions.

Change-Id: I72a0a4f68503b7c143cbe6c6f13cfbdc08e6ccbb