Fix bug "AttributeError: 'generator' object has no attribute 'next'"
1. the bug:
   Captured traceback:
   ~~~~~~~~~~~~~~~~~~~
	Traceback (most recent call last):

	File "/opt/stack/freezer/freezer/tests/unit/scheduler/test_utils.py", line 53, in test_find_config_files_path
	ret = utils.find_config_files(temp_path)

	File "/opt/stack/freezer/freezer/scheduler/utils.py", line 53, in find_config_files
	for fname in os.walk(expanded_path).next()[2]:

	AttributeError: 'generator' object has no attribute 'next'

2. fix:
To get iterobject next element  is  changed to next(iterobject,defalt) in python3.x.

Change-Id: I558bbfecb4a9670a10b1fc649821d88619b7917c